import type { PulseLatest, PulseSignal } from "../types";
import { SAMPLE_PULSE } from "../data/samplePulse";

/**
 * Load the latest public pulse signals generated by the scheduled
 * GitHub Actions job. Falls back to bundled sample data so the app
 * always renders something useful (e.g. first run, offline, fetch error).
 */
export async function loadLatestPulse(): Promise<{
  data: PulseLatest;
  isSample: boolean;
}> {
  try {
    const res = await fetch(`${import.meta.env.BASE_URL}data/latest.json`, {
      cache: "no-cache",
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = (await res.json()) as PulseLatest;
    if (!Array.isArray(data.signals) || data.signals.length === 0) {
      throw new Error("empty pulse file");
    }
    // Defense in depth: never render a non-http(s) link, whatever the file says.
    data.signals = data.signals.filter((s) => {
      try {
        const u = new URL(s.url);
        return u.protocol === "http:" || u.protocol === "https:";
      } catch {
        return false;
      }
    });
    if (data.signals.length === 0) throw new Error("no valid signals");
    return { data, isSample: false };
  } catch {
    return { data: SAMPLE_PULSE, isSample: true };
  }
}

export function topSignals(data: PulseLatest, n: number): PulseSignal[] {
  return [...data.signals].sort((a, b) => b.score - a.score).slice(0, n);
}
